### ISSUE TITLE
This fork of react-sortable-tree only works on React 17

### ISSUE THREAD

**Issue by JPStrydom** [nosferatu500/react-sortable-tree#16]
# Is there a reason this fork only supports React 17? The original supports 16, so I'm sure this one should be compatible as well. Perhaps the peer dependency is just incorrect?

**Comment by nosferatu500** [comment]
Is there a reason you can't upgrade to React 17? React 18 is on the way.

**Comment by nosferatu500** [comment]
I don't mean to be rude but as I mentioned in the description: I made this fork just for myself because I need this library for my own project. I am using React 17 (the reason of this fork). I'm not focused on supporting everything or supporting it for other people. If you need any features or bug fixes - PR is welcome. As I said, I only fix bugs if they are related to my own project. Everything else - PR is always welcome.

**Comment by kmvan** [comment]
react 17/18 works.

**Comment by nosferatu500** [comment]
I have no plans to support react 16 or below
